var g1 = {
    "data": [
        {
            "line": {
                "dash": "dot",
                "color": "#00BEBB", // mynote: color of "Attacks" line
                "shape": "linear"
            },
            "mode": "lines",
            "name": "Attacks",
            "opacity": 0.8,
            "type": "scatter",
            "hoverlabel": {
              "namelength": -1,
              "bordercolor": "white",
            },
            "x": [
                "8/19",
                "8/20",
                "8/21",
                "8/22",
                "8/23",
                "8/24",
                "8/25",
                "8/26",
                "8/27",
                "8/28",
                "8/29",
                "8/30",
                "8/31",
                "9/1",
                "9/2",
                "9/3",
                "9/4",
                "9/5",
                "9/6",
                "9/7",
                "9/8",
                "9/9",
                "9/10",
                "9/11",
                "9/12",
                "9/13",
                "9/14",
                "9/15",
                "9/16",
                "9/17",
                "9/18",
                "9/19",
                "9/20",
                "9/21",
                "9/22",
                "9/23",
                "9/24",
                "9/25",
                "9/26",
                "9/27",
                "9/28",
                "9/29"
            ],
            "y": [
                "1",
                "1",
                "1",
                "0",
                "1",
                "1",
                "0",
                "1",
                "1",
                "1",
                "1",
                "8",
                "56",
                "143",
                "116",
                "54",
                "46",
                "36",
                "20",
                "28",
                "12",
                "11",
                "5",
                "5",
                "1",
                "3",
                "0",
                "1",
                "4",
                "2",
                "3",
                "0",
                "0",
                "2",
                "1",
                "1",
                "1",
                "1",
                "1",
                "1",
                "0",
                "0"
            ],
            "hovertemplate": ""
        },
        {
            "line": {
                "dash": "dot",
                "color": "#D10E00" // mynote: color of "Deaths" line
            },
            "mode": "lines",
            "name": "Deaths",
            "opacity": 0.8,
            "type": "scatter",
            "hoverlabel": {
              "namelength": -1,
              "bordercolor": "white",
            },
            "x": [
                "8/19",
                "8/20",
                "8/21",
                "8/22",
                "8/23",
                "8/24",
                "8/25",
                "8/26",
                "8/27",
                "8/28",
                "8/29",
                "8/30",
                "8/31",
                "9/1",
                "9/2",
                "9/3",
                "9/4",
                "9/5",
                "9/6",
                "9/7",
                "9/8",
                "9/9",
                "9/10",
                "9/11",
                "9/12",
                "9/13",
                "9/14",
                "9/15",
                "9/16",
                "9/17",
                "9/18",
                "9/19",
                "9/20",
                "9/21",
                "9/22",
                "9/23",
                "9/24",
                "9/25",
                "9/26",
                "9/27",
                "9/28",
                "9/29"
            ],
            "y": [
                "1",
                "0",
                "2",
                "0",
                "0",
                "2",
                "0",
                "0",
                "1",
                "0",
                "1",
                "2",
                "3",
                "70",
                "127",
                "76",
                "71",
                "45",
                "37",
                "32",
                "30",
                "24",
                "18",
                "15",
                "6",
                "13",
                "6",
                "8",
                "6",
                "5",
                "2",
                "3",
                "0",
                "0",
                "2",
                "3",
                "0",
                "0",
                "2",
                "0",
                "2",
                "1"
            ],
            "stackgroup": null
        },
        {
            "line": {
                "dash": "solid",
                "color": "#00BEBB" // mynote: color of "Cumulative Attacks" line
            },
            "mode": "lines",
            "name": "Cumulative Attacks",
            "opacity": 0.6,
            "type": "scatter",
            "hoverlabel": {
              "namelength": -1,
              "bordercolor": "white",
            },
            "x": [
                "8/19",
                "8/20",
                "8/21",
                "8/22",
                "8/23",
                "8/24",
                "8/25",
                "8/26",
                "8/27",
                "8/28",
                "8/29",
                "8/30",
                "8/31",
                "9/1",
                "9/2",
                "9/3",
                "9/4",
                "9/5",
                "9/6",
                "9/7",
                "9/8",
                "9/9",
                "9/10",
                "9/11",
                "9/12",
                "9/13",
                "9/14",
                "9/15",
                "9/16",
                "9/17",
                "9/18",
                "9/19",
                "9/20",
                "9/21",
                "9/22",
                "9/23",
                "9/24",
                "9/25",
                "9/26",
                "9/27",
                "9/28",
                "9/29"
            ],
            "y": [
                "1",
                "2",
                "3",
                "3",
                "4",
                "5",
                "5",
                "6",
                "7",
                "8",
                "9",
                "17",
                "73",
                "216",
                "332",
                "386",
                "432",
                "468",
                "488",
                "516",
                "528",
                "539",
                "544",
                "549",
                "550",
                "553",
                "553",
                "554",
                "558",
                "560",
                "563",
                "563",
                "563",
                "565",
                "566",
                "567",
                "568",
                "569",
                "570",
                "571",
                "571",
                "571"
            ],
            "stackgroup": null
        },
        {
            "line": {
                "color": "#D10E00" // color of "cumulative deaths" line
            },
            "mode": "lines",
            "name": "Cumulative Deaths",
            "opacity": 0.6,
            "type": "scatter",
            "hoverlabel": {
              "namelength": -1,
              "bordercolor": "white",
        },
            "x": [
                "8/19",
                "8/20",
                "8/21",
                "8/22",
                "8/23",
                "8/24",
                "8/25",
                "8/26",
                "8/27",
                "8/28",
                "8/29",
                "8/30",
                "8/31",
                "9/1",
                "9/2",
                "9/3",
                "9/4",
                "9/5",
                "9/6",
                "9/7",
                "9/8",
                "9/9",
                "9/10",
                "9/11",
                "9/12",
                "9/13",
                "9/14",
                "9/15",
                "9/16",
                "9/17",
                "9/18",
                "9/19",
                "9/20",
                "9/21",
                "9/22",
                "9/23",
                "9/24",
                "9/25",
                "9/26",
                "9/27",
                "9/28",
                "9/29"
            ],
            "y": [
                "1",
                "1",
                "3",
                "3",
                "3",
                "5",
                "5",
                "5",
                "6",
                "6",
                "7",
                "9",
                "12",
                "82",
                "209",
                "285",
                "356",
                "401",
                "438",
                "470",
                "500",
                "524",
                "542",
                "557",
                "563",
                "576",
                "582",
                "590",
                "596",
                "601",
                "603",
                "606",
                "606",
                "606",
                "608",
                "611",
                "611",
                "611",
                "613",
                "613",
                "615",
                "616"
            ],
            "stackgroup": null
        }
    ],
    "layout": {
        "title": {
            "x": 0.5,
            "font": {
                "size": 18,
                "family": "Oxygen"
            },
            "text": "1854 Cholera Outbreak in London"
        },
        "xaxis": {
            "type": "category",
            "range": [ 0, 41 ],
            "ticks": "",
            "title": {
                "font": {
                    "family": "Oxygen"
                },
                "text": "Date"
            },
            "nticks": 20,
            "showline": false,
            "tickfont": {
                "family": "Assistant"
            },
            "autorange": true,
            "showspikes": false,
        },
        "yaxis": {
            "type": "linear",
            "dtick": 100,
            "range": [ -34.25, 650.25 ],
            "title": {
                "font": {
                    "family": "Oxygen"
                },
                "text": "Number of Occurrences"
            },
            "tickfont": {
                "family": "Assistant"
            },
            "tickmode": "linear",
            "autorange": true
        },
        "legend": {
            "font": {
                "family": "Oxygen"
            }
        },
        "autosize": true,
        "dragmode": "zoom",
        "template": {
            "data": {
                "bar": [
                    {
                        "type": "bar",
                        "marker": {
                            "colorbar": {
                                "ticks": "",
                                "outlinewidth": 0
                            }
                        }
                    }
                ]
            },
            "layout": {
                "font": {
                    "color": "#2a3f5f"
                },
                "xaxis": {
                    "ticks": "",
                    "gridcolor": "#EBF0F8",
                    "linecolor": "#EBF0F8",
                    "automargin": true,
                    "zerolinecolor": "#EBF0F8",
                    "zerolinewidth": 2
                },
                "yaxis": {
                    "ticks": "",
                    "gridcolor": "#EBF0F8",
                    "linecolor": "#EBF0F8",
                    "automargin": true,
                    "zerolinecolor": "#EBF0F8",
                    "zerolinewidth": 2
                },
                "legend": {
                    "x": 1.0,
                    "y": 0.8
                },
                "hovermode": "closest",
                "colorscale": { },
                "plot_bgcolor": "white",
                "paper_bgcolor": "white",
                "shapedefaults": {
                    "line": {
                        "width": 0
                    },
                    "opacity": 0.4,
                    "fillcolor": "#506784"
                },
                "annotationdefaults": {
                    "arrowhead": 0,
                    "arrowcolor": "#506784",
                    "arrowwidth": 1
                }
            },
            "themeRef": "PLOTLY_WHITE"
        },
        "hoverlabel": {
            "font": {
                "family": "Assistant"
            }
        }
    },
    "frames": []
}
